spring.application.name=packops-backend
spring.datasource.url=jdbc:h2:mem:packopsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret lokale Entwicklung
app.security.jwt.secret=packops-super-secret-key-for-development-only-change-later-123456789
app.security.jwt.issuer=packops-backend
app.security.jwt.expiration-minutes=120